export enum FieldType {
    text = 'text',
    textLocalized = 'textLocalized',
    email = 'email',
    password = 'password',
    number = 'number',
    url = 'url',
    file = 'file',
    editor = 'editor',
    editorLocalized = 'editorLocalized',
    date = 'date',
    time = 'time',
    weekDays = 'weekDays',
    dropdown = 'dropdown',
    checkbox = 'checkbox',
    radio = 'radio',
    entity = 'entity',
    group = 'group',
    divider = 'divider',
    array = 'array',
    autoComplete = 'autoComplete',
    color = 'color',
    chips = 'chips',
    colorPicker = 'colorPicker',
}