
/* This file should contain All EndPoint Routes Across all the application*/
/* Follow the Naming Convention*/
// const uri = 'http://localhost:3050/v1';
// const uri = 'https://edupromise.remabackend.com/v1';
const uri = 'http://ec2-54-75-162-129.eu-west-1.compute.amazonaws.com:8080/v1';
export const API_URLS = {
  auth: {
    auth: uri + '/auth/login',
    changePassword: uri + '/Auth/changePassword',
    resetPassword: uri + '/Auth/resetPassword',
    register: uri + '/register',
  },
  File: {
    upload: 'https://file.remabackend.com/File/upload?project=EWJ',
    UploadMultiple:  'https://file.remabackend.com/File/uploadMultiple?project=EWJ',
    delete: uri + '/File',
  },
  appsettings: {
    post: uri + '/appsettings',
    get: uri + '/appsettings',
    put: uri + '/appsettings/{entityId}',
    delete: uri + '/appsettings/{entityId}',
  },
  Employee: {
    post: uri + '/Employee',
    get: uri + '/Employee/all',
    getOne: uri + '/Employee/{entityId}',
    put: uri + '/Employee/{entityId}',
    delete: uri + '/Employee/{entityId}',
  },
  Location: {
    post: uri + '/Location',
    get: uri + '/Location/all',
    getOne: uri + '/Location/{entityId}',
    put: uri + '/Location/{entityId}',
    delete: uri + '/Location/{entityId}',
  },
  Notification: {
    post: uri + '/Notification',
    get: uri + '/Notification/all',
    getOne: uri + '/Notification/{entityId}',
    put: uri + '/Notification/{entityId}',
    delete: uri + '/Notification/{entityId}',
  },
  specialRequest: {
    post: uri + '/specialRequest',
    get: uri + '/specialRequest/all',
    getOne: uri + '/specialRequest/{entityId}',
    put: uri + '/specialRequest/{entityId}',
    delete: uri + '/specialRequest/{entityId}',
  },
  review: {
    post: uri + '/review',
    get: uri + '/review/all',
    getOne: uri + '/review/{entityId}',
    put: uri + '/review/{entityId}',
    delete: uri + '/review/{entityId}',
  },
  employeeInContactWith: {
    post: uri + '/employeeInContactWith',
    get: uri + '/employeeInContactWith/all',
    getOne: uri + '/employeeInContactWith/{entityId}',
    put: uri + '/employeeInContactWith/{entityId}',
    delete: uri + '/employeeInContactWith/{entityId}',
  },
  answer: {
    post: uri + '/answer',
    get: uri + '/answer/all',
    getOne: uri + '/answer/{entityId}',
    put: uri + '/answer/{entityId}',
    delete: uri + '/answer/{entityId}',
  },
  Course: {
    post: uri + '/Course',
    get: uri + '/Course/all',
    getOne: uri + '/Course/{entityId}',
    put: uri + '/Course/{entityId}',
    delete: uri + '/Course/{entityId}',
  },
  Lesson: {
    post: uri + '/Lesson',
    get: uri + '/Lesson/all',
    getOne: uri + '/Lesson/{entityId}',
    put: uri + '/Lesson/{entityId}',
    delete: uri + '/Lesson/{entityId}',
  },
  CronExpression: {
    post: uri + '/CronExpression',
    get: uri + '/CronExpression/all',
    getOne: uri + '/CronExpression/{entityId}',
    put: uri + '/CronExpression/{entityId}',
    delete: uri + '/CronExpression/{entityId}',
  },
  Survey: {
    post: uri + '/Survey',
    get: uri + '/Survey/all',
    getOne: uri + '/Survey/{entityId}',
    put: uri + '/Survey/{entityId}',
    delete: uri + '/Survey/{entityId}',
  },
  Question: {
    post: uri + '/Question',
    get: uri + '/Question/all',
    getOne: uri + '/Question/{entityId}',
    put: uri + '/Question/{entityId}',
    delete: uri + '/Question/{entityId}',
  },
  Country: {
    post: uri + '/Country',
    get: uri + '/Country/all',
    getOne: uri + '/Country/{entityId}',
    put: uri + '/Country/{entityId}',
    delete: uri + '/Country/{entityId}',
  },
  City: {
    post: uri + '/City',
    get: uri + '/City/all',
    getOne: uri + '/City/{entityId}',
    put: uri + '/City/{entityId}',
    delete: uri + '/City/{entityId}',
  },
  User: {
    post: uri + '/User',
    get: uri + '/User/all',
    getOne: uri + '/User/{entityId}',
    put: uri + '/User/{entityId}',
    delete: uri + '/User/{entityId}',
    upload: uri + '/User/upload',
  },
  CRM: {
    post: uri + '/CRM/Label',
    get: uri + '/CRM/Label/all',
    getOne: uri + '/CRM/Label/{entityId}',
    put: uri + '/CRM/Label/{entityId}',
    delete: uri + '/CRM/Label/{entityId}',
  },

  University: {
    post: uri + '/University',
    get: uri + '/University/all',
    getOne: uri + '/University/{entityId}',
    put: uri + '/University/{entityId}',
    delete: uri + '/University/{entityId}',
  },
  Team: {
    post: uri + '/Team',
    get: uri + '/Team/all',
    getOne: uri + '/Team/{entityId}',
    put: uri + '/Team/{entityId}',
    delete: uri + '/Team/{entityId}',
  },
  Degree: {
    post: uri + '/Degree',
    get: uri + '/Degree/all',
    getOne: uri + '/Degree/{entityId}',
    put: uri + '/Degree/{entityId}',
    delete: uri + '/Degree/{entityId}',
  },
  Language: {
    post: uri + '/Language',
    get: uri + '/Language/all',
    getOne: uri + '/Language/{entityId}',
    put: uri + '/Language/{entityId}',
    delete: uri + '/Language/{entityId}',
  },
  Department: {
    post: uri + '/Department',
    get: uri + '/Department/all',
    getOne: uri + '/Department/{entityId}',
    put: uri + '/Department/{entityId}',
    delete: uri + '/Department/{entityId}',
  },
  UniversityDepartment: {
    post: uri + '/UniversityDepartment',
    get: uri + '/UniversityDepartment/all',
    getOne: uri + '/UniversityDepartment/{entityId}',
    put: uri + '/UniversityDepartment/{entityId}',
    delete: uri + '/UniversityDepartment/{entityId}',
  },
  Article: {
    post: uri + '/Article',
    get: uri + '/Article/all',
    check: uri + '/Article/check?slug=',
    getOne: uri + '/Article/{entityId}',
    put: uri + '/Article/{entityId}',
    delete: uri + '/Article/{entityId}',
  },
  UniversityArticle: {
    post: uri + '/UniversityArticle',
    get: uri + '/UniversityArticle/all',
    check: uri + '/UniversityArticle/check?slug=',
    getOne: uri + '/UniversityArticle/{entityId}',
    put: uri + '/UniversityArticle/{entityId}',
    delete: uri + '/UniversityArticle/{entityId}',
  },
  Rank: {
    post: uri + '/Rank',
    get: uri + '/Rank/all',
    getOne: uri + '/Rank/{entityId}',
    put: uri + '/Rank/{entityId}',
    delete: uri + '/Rank/{entityId}',
  },
  SeoOptions: {
    post: uri + '/SeoOptions',
    get: uri + '/SeoOptions/all',
    getOne: uri + '/SeoOptions/{entityId}',
    put: uri + '/SeoOptions/{entityId}',
    delete: uri + '/SeoOptions/{entityId}',
  },
  Category: {
    post: uri + '/Category',
    get: uri + '/Category/all',
    getOne: uri + '/Category/{entityId}',
    put: uri + '/Category/{entityId}',
    delete: uri + '/Category/{entityId}',
  },
  Board: {
    post: uri + '/Board',
    get: uri + '/Board/all',
    getOne: uri + '/Board/{entityId}',
    put: uri + '/Board/{entityId}',
    delete: uri + '/Board/{entityId}',
  },
  OurService: {
    post: uri + '/OurService',
    get: uri + '/OurService/all',
    getOne: uri + '/OurService/{entityId}',
    put: uri + '/OurService/{entityId}',
    delete: uri + '/OurService/{entityId}',
  },
  Advertise: {
    post: uri + '/Advertise',
    get: uri + '/Advertise/all',
    getOne: uri + '/Advertise/{entityId}',
    put: uri + '/Advertise/{entityId}',
    delete: uri + '/Advertise/{entityId}',
  },
  Page: {
    post: uri + '/Page',
    get: uri + '/Page/all',
    getOne: uri + '/Page/{entityId}',
    put: uri + '/Page/{entityId}',
    delete: uri + '/Page/{entityId}',
  },
  Section: {
    post: uri + '/Section',
    get: uri + '/Section/all',
    getOne: uri + '/Section/{entityId}',
    put: uri + '/Section/{entityId}',
    delete: uri + '/Section/{entityId}',
  },
  Application: {
    transfer: uri + '/Application/transfer'
  },
  Comment: {
    post: uri + '/comment',
    get: uri + '/comment/all',
    getOne: uri + '/comment/{entityId}',
    put: uri + '/comment/{entityId}',
    delete: uri + '/comment/{entityId}',
  },
  Openion: {
    post: uri + '/Openion',
    get: uri + '/Openion/all',
    getOne: uri + '/Openion/{entityId}',
    put: uri + '/Openion/{entityId}',
    delete: uri + '/Openion/{entityId}',
  },

};